/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerifikationerRouteImport } from './routes/_app.verifikationer'
import { Route as AppRapporterRouteImport } from './routes/_app.rapporter'
import { Route as AppKvittonRouteImport } from './routes/_app.kvitton'
import { Route as AppKontonRouteImport } from './routes/_app.konton'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnvandareRouteImport } from './routes/_app.anvandare'
import { Route as ApiPublicNotifySignupRouteImport } from './routes/api/public/notify-signup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifikationerRoute = AppVerifikationerRouteImport.update({
  id: '/verifikationer',
  path: '/verifikationer',
  getParentRoute: () => AppRoute,
} as any)
const AppRapporterRoute = AppRapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => AppRoute,
} as any)
const AppKvittonRoute = AppKvittonRouteImport.update({
  id: '/kvitton',
  path: '/kvitton',
  getParentRoute: () => AppRoute,
} as any)
const AppKontonRoute = AppKontonRouteImport.update({
  id: '/konton',
  path: '/konton',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnvandareRoute = AppAnvandareRouteImport.update({
  id: '/anvandare',
  path: '/anvandare',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicNotifySignupRoute = ApiPublicNotifySignupRouteImport.update({
  id: '/api/public/notify-signup',
  path: '/api/public/notify-signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anvandare': typeof AppAnvandareRoute
  '/dashboard': typeof AppDashboardRoute
  '/konton': typeof AppKontonRoute
  '/kvitton': typeof AppKvittonRoute
  '/rapporter': typeof AppRapporterRoute
  '/verifikationer': typeof AppVerifikationerRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anvandare': typeof AppAnvandareRoute
  '/dashboard': typeof AppDashboardRoute
  '/konton': typeof AppKontonRoute
  '/kvitton': typeof AppKvittonRoute
  '/rapporter': typeof AppRapporterRoute
  '/verifikationer': typeof AppVerifikationerRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/anvandare': typeof AppAnvandareRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/konton': typeof AppKontonRoute
  '/_app/kvitton': typeof AppKvittonRoute
  '/_app/rapporter': typeof AppRapporterRoute
  '/_app/verifikationer': typeof AppVerifikationerRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anvandare'
    | '/dashboard'
    | '/konton'
    | '/kvitton'
    | '/rapporter'
    | '/verifikationer'
    | '/api/public/notify-signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/anvandare'
    | '/dashboard'
    | '/konton'
    | '/kvitton'
    | '/rapporter'
    | '/verifikationer'
    | '/api/public/notify-signup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/anvandare'
    | '/_app/dashboard'
    | '/_app/konton'
    | '/_app/kvitton'
    | '/_app/rapporter'
    | '/_app/verifikationer'
    | '/api/public/notify-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicNotifySignupRoute: typeof ApiPublicNotifySignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verifikationer': {
      id: '/_app/verifikationer'
      path: '/verifikationer'
      fullPath: '/verifikationer'
      preLoaderRoute: typeof AppVerifikationerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapporter': {
      id: '/_app/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof AppRapporterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kvitton': {
      id: '/_app/kvitton'
      path: '/kvitton'
      fullPath: '/kvitton'
      preLoaderRoute: typeof AppKvittonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/konton': {
      id: '/_app/konton'
      path: '/konton'
      fullPath: '/konton'
      preLoaderRoute: typeof AppKontonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anvandare': {
      id: '/_app/anvandare'
      path: '/anvandare'
      fullPath: '/anvandare'
      preLoaderRoute: typeof AppAnvandareRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/notify-signup': {
      id: '/api/public/notify-signup'
      path: '/api/public/notify-signup'
      fullPath: '/api/public/notify-signup'
      preLoaderRoute: typeof ApiPublicNotifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnvandareRoute: typeof AppAnvandareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKontonRoute: typeof AppKontonRoute
  AppKvittonRoute: typeof AppKvittonRoute
  AppRapporterRoute: typeof AppRapporterRoute
  AppVerifikationerRoute: typeof AppVerifikationerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnvandareRoute: AppAnvandareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKontonRoute: AppKontonRoute,
  AppKvittonRoute: AppKvittonRoute,
  AppRapporterRoute: AppRapporterRoute,
  AppVerifikationerRoute: AppVerifikationerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicNotifySignupRoute: ApiPublicNotifySignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
